### ISSUE TITLE
Releases don't install in ALF 5.0c

### ISSUE THREAD

**Issue by deajan** [rouxemmanuel/images#1]
Hello,

I've reseted my test VM to a fresh ALF 5.0c and tried to install the amp files from github.com/rouxemmanuel/images

When i run amps_setup.sh, i get the following:

```
[root@localhost ~]# /opt/alfresco-5.0.c/bin/apply_amps.sh

Found java executable in /opt/alfresco-5.0.c/java

This script will apply all the AMPs in amps and amps_share to the alfresco.war and share.war files in /opt/alfresco-5.0.c/tomcat/webapps
Press control-c to stop this script . . .
Press any other key to continue . . .

java.io.FileNotFoundException: /opt/alfresco-5.0.c/amps/digitalSigningAlfresco.amp/module.properties
        at de.schlichtherle.truezip.file.TFileInputStream.newInputStream(TFileInputStream.java:108)
        at de.schlichtherle.truezip.file.TFileInputStream.<init>(TFileInputStream.java:81)
        at org.alfresco.repo.module.tool.ModuleDetailsHelper.createModuleDetailsFromPropertyLocation(ModuleDetailsHelper.java:74)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModule(ModuleManagementTool.java:228)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:171)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:154)
        at org.alfresco.repo.module.tool.ModuleManagementTool.main(ModuleManagementTool.java:877)
Caused by: java.util.zip.ZipException: Expected Local File Header or (ZIP64) End Of Central Directory Record!
        at de.schlichtherle.truezip.zip.RawZipFile.checkZipFileSignature(RawZipFile.java:179)
        at de.schlichtherle.truezip.zip.RawZipFile.<init>(RawZipFile.java:148)
        at de.schlichtherle.truezip.zip.RawZipFile.<init>(RawZipFile.java:129)
        at de.schlichtherle.truezip.fs.archive.zip.ZipInputShop.<init>(ZipInputShop.java:46)
        at de.schlichtherle.truezip.fs.archive.zip.ZipDriver.newInputShop(ZipDriver.java:487)
        at de.schlichtherle.truezip.fs.archive.zip.ZipDriver.newInputShop(ZipDriver.java:470)
        at de.schlichtherle.truezip.fs.archive.FsTargetArchiveController.mount0(FsTargetArchiveController.java:220)
        at de.schlichtherle.truezip.fs.archive.FsTargetArchiveController.mount(FsTargetArchiveController.java:175)
        at de.schlichtherle.truezip.fs.archive.FsFileSystemArchiveController$ResetFileSystem.autoMount(FsFileSystemArchiveController.java:86)
        at de.schlichtherle.truezip.fs.archive.FsFileSystemArchiveController.autoMount(FsFileSystemArchiveController.java:38)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController.autoMount(FsArchiveController.java:114)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController$Input.getLocalTarget(FsArchiveController.java:198)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController$Input.getDelegate(FsArchiveController.java:209)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.getBoundSocket(DelegatingInputSocket.java:43)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.newInputStream(DelegatingInputSocket.java:63)
        at de.schlichtherle.truezip.fs.archive.FsContextController$Input.newInputStream(FsContextController.java:304)
        at de.schlichtherle.truezip.fs.FsResourceController$Input.newInputStream(FsResourceController.java:257)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.newInputStream(DelegatingInputSocket.java:63)
        at de.schlichtherle.truezip.fs.FsSyncController$Input.newInputStream(FsSyncController.java:412)
        at de.schlichtherle.truezip.fs.FsLockController$Input$1NewInputStream.call(FsLockController.java:494)
        at de.schlichtherle.truezip.fs.FsLockController$Input$1NewInputStream.call(FsLockController.java:491)
        at de.schlichtherle.truezip.fs.FsLockController.locked(FsLockController.java:364)
        at de.schlichtherle.truezip.fs.FsLockController.writeLocked(FsLockController.java:303)
        at de.schlichtherle.truezip.fs.FsLockController$Input.newInputStream(FsLockController.java:499)
        at de.schlichtherle.truezip.fs.FsFinalizeController$Input.newInputStream(FsFinalizeController.java:176)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input$NewInputStream.call(FsFalsePositiveController.java:363)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input$NewInputStream.call(FsFalsePositiveController.java:356)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$TryChild.call(FsFalsePositiveController.java:536)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController.call(FsFalsePositiveController.java:104)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input.newInputStream(FsFalsePositiveController.java:353)
        at de.schlichtherle.truezip.file.TFileInputStream.newInputStream(TFileInputStream.java:104)
        ... 6 more
02100001 An error was encountered during deployment of the AMP into the WAR: 02100000 Unable to load module details from property file. File Not Found, /opt/alfresco-5.0.c/amps/digitalSigningAlfresco.amp/module.properties
Module 'org_alfresco_module_wcmquickstart' installed in '/opt/alfresco-5.0.c/tomcat/webapps/alfresco.war'
   -    Title:        Web Quick Start
   -    Version:      1.0
   -    Install Date: Tue Mar 10 15:04:31 CET 2015
   -    Description:   Web Quick Start
Module 'org.alfresco.module.vti' installed in '/opt/alfresco-5.0.c/tomcat/webapps/alfresco.war'
   -    Title:        Vti
   -    Version:      1.3
   -    Install Date: Tue Mar 10 15:04:24 CET 2015
   -    Description:   Alfresco Vti Extension, provides Sharepoint protocol
java.io.FileNotFoundException: /opt/alfresco-5.0.c/amps_share/digitalSigningShare.amp/module.properties
        at de.schlichtherle.truezip.file.TFileInputStream.newInputStream(TFileInputStream.java:108)
        at de.schlichtherle.truezip.file.TFileInputStream.<init>(TFileInputStream.java:81)
        at org.alfresco.repo.module.tool.ModuleDetailsHelper.createModuleDetailsFromPropertyLocation(ModuleDetailsHelper.java:74)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModule(ModuleManagementTool.java:228)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:171)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:154)
        at org.alfresco.repo.module.tool.ModuleManagementTool.main(ModuleManagementTool.java:877)
Caused by: java.util.zip.ZipException: Expected Local File Header or (ZIP64) End Of Central Directory Record!
        at de.schlichtherle.truezip.zip.RawZipFile.checkZipFileSignature(RawZipFile.java:179)
        at de.schlichtherle.truezip.zip.RawZipFile.<init>(RawZipFile.java:148)
        at de.schlichtherle.truezip.zip.RawZipFile.<init>(RawZipFile.java:129)
        at de.schlichtherle.truezip.fs.archive.zip.ZipInputShop.<init>(ZipInputShop.java:46)
        at de.schlichtherle.truezip.fs.archive.zip.ZipDriver.newInputShop(ZipDriver.java:487)
        at de.schlichtherle.truezip.fs.archive.zip.ZipDriver.newInputShop(ZipDriver.java:470)
        at de.schlichtherle.truezip.fs.archive.FsTargetArchiveController.mount0(FsTargetArchiveController.java:220)
        at de.schlichtherle.truezip.fs.archive.FsTargetArchiveController.mount(FsTargetArchiveController.java:175)
        at de.schlichtherle.truezip.fs.archive.FsFileSystemArchiveController$ResetFileSystem.autoMount(FsFileSystemArchiveController.java:86)
        at de.schlichtherle.truezip.fs.archive.FsFileSystemArchiveController.autoMount(FsFileSystemArchiveController.java:38)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController.autoMount(FsArchiveController.java:114)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController$Input.getLocalTarget(FsArchiveController.java:198)
        at de.schlichtherle.truezip.fs.archive.FsArchiveController$Input.getDelegate(FsArchiveController.java:209)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.getBoundSocket(DelegatingInputSocket.java:43)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.newInputStream(DelegatingInputSocket.java:63)
        at de.schlichtherle.truezip.fs.archive.FsContextController$Input.newInputStream(FsContextController.java:304)
        at de.schlichtherle.truezip.fs.FsResourceController$Input.newInputStream(FsResourceController.java:257)
        at de.schlichtherle.truezip.socket.DelegatingInputSocket.newInputStream(DelegatingInputSocket.java:63)
        at de.schlichtherle.truezip.fs.FsSyncController$Input.newInputStream(FsSyncController.java:412)
        at de.schlichtherle.truezip.fs.FsLockController$Input$1NewInputStream.call(FsLockController.java:494)
        at de.schlichtherle.truezip.fs.FsLockController$Input$1NewInputStream.call(FsLockController.java:491)
        at de.schlichtherle.truezip.fs.FsLockController.locked(FsLockController.java:364)
        at de.schlichtherle.truezip.fs.FsLockController.writeLocked(FsLockController.java:303)
        at de.schlichtherle.truezip.fs.FsLockController$Input.newInputStream(FsLockController.java:499)
        at de.schlichtherle.truezip.fs.FsFinalizeController$Input.newInputStream(FsFinalizeController.java:176)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input$NewInputStream.call(FsFalsePositiveController.java:363)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input$NewInputStream.call(FsFalsePositiveController.java:356)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$TryChild.call(FsFalsePositiveController.java:536)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController.call(FsFalsePositiveController.java:104)
        at de.schlichtherle.truezip.fs.FsFalsePositiveController$1Input.newInputStream(FsFalsePositiveController.java:353)
        at de.schlichtherle.truezip.file.TFileInputStream.newInputStream(TFileInputStream.java:104)
        ... 6 more
02100001 An error was encountered during deployment of the AMP into the WAR: 02100000 Unable to load module details from property file. File Not Found, /opt/alfresco-5.0.c/amps_share/digitalSigningShare.amp/module.properties
Module 'org_alfresco_module_wcmquickstartshare' installed in '/opt/alfresco-5.0.c/tomcat/webapps/share.war'
   -    Title:        Web Quick Start Share
   -    Version:      1.1
   -    Install Date: Tue Mar 10 15:04:57 CET 2015
   -    Description:   Web Quick Start Share Module
About to clean out /opt/alfresco-5.0.c/tomcat/webapps/alfresco and share directories and temporary files...
Press control-c to stop this script . . .
Press any other key to continue . . .
```

The amp files from the googlecode page installs on the same VM.

Regards,
Ozy.

**Comment by rouxemmanuel** [comment]
Hello,
I've open the two AMP with 7zip and the file module.properties is a the root of each AMP.

Regards,
Emmanuel

**Comment by deajan** [comment]
Hi,

My bad, i downloaded with wget the same way i did from the earlier svn repo, and forgot to use the 'raw' link.

Sorry for the inconvenience.
